# Header
menu:
  主页: /
  所有文章: /archives
  # 随笔: /tags/随笔

# SubNav
subnav:
  github: "https://github.com/matrixbirds"
  weibo: "http://weibo.com/angry0bits"
  rss: "#"
  zhihu: "#"
  #douban: "#"
  #mail: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: "http://7xivqf.com1.z0.glb.clouddn.com/gitcafepsb.jpeg"
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: "matrixbirds"
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
    Shiningray: "http://shiningray.cn/"
    Zhihu_LiQi: "http://liqi.wtf/"
    Lellansin: "http://www.lellansin.com"
    Kimmg: "http://kimmg.com"
    花姐: "http://seiran.mist.so/"

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 会写段子,会演奏,爱好开源,正在学西语,霓虹语,偶尔画画的rubyist ******************* ヾ (o ° ω ° O ) ノ゙
